config/routes.rb
Rails.application.routes.draw do
	resources :archives, :only => [:index, :create, :edit, :destroy, :update] do
		collection do
			get 'category_list'
			get 'tree'
			get 'toggle_testing'
		end
	end

	resources :federations
	resources :genres
	resources :disciplines
	resources :white_lists

	post '/corrections' => 'corrections#create'

	resources :exhibits, :only => [:index, :create, :destroy] do
		collection do
			get 'test_create_good'
			get 'test_create_bad'
			get 'test_destroy_good'
			get 'test_destroy_bad'
		end
	end

	resources :locals, :only => [:index, :create, :destroy, :update ] do
		collection do
			get 'test_search_good'
			get 'test_search_bad'
		end
	end

	devise_for :users

	get "home/index"

   resources :pages, :only => [:index]

	resources :search, :only => [:index] do
		collection do
			get 'autocomplete'
			get 'names'
			get 'totals'
			get 'details'
			get 'compare'
      get 'languages'
		end
	end

	resources :test_sort, :only => [:index]

	get "/test_exception_notifier" => "home#test_exception_notifier"

  put "/documents/tw/enable" => "documents#typewright_enable"
  put "/documents/tw/disable" => "documents#typewright_disable"

  get "/documents/title" => "documents#title"

  root :to => "home#index"
	post "/" => "home#index"

end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
#	before_filter :must_be_logged_in
	before_filter :must_be_logged_in, :except => [:index]
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  
  # GET /genres
  # GET /genres.json
  # GET /genres.xml
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  # GET /genres/1.xml
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  # POST /genres.xml
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
        format.xml  { render :xml => @genre, :status => :created, :location => @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  # PATCH/PUT /genres/1.xml
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
        format.xml  { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  # DELETE /genres/1.xml
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
      format.xml  { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
	<h2>Editing genre</h2>

	<%= render 'form' %>

	<%= link_to 'Show', @genre %> |
	<%= link_to 'Back', genres_path %>
</div>

app/views/genres/index.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
	<h2>All Genres</h2>
  <%= make_xml_path(request.fullpath) %><br/>
  <%= make_json_path(request.fullpath) %>

	<table class="results">
	  <tr>
		<th>Name</th>
	<% if user_signed_in? %>
		<th></th>
		<th></th>
		<th></th>
	<% end %>
	  </tr>

	<% @genres.each do |genre| %>
	  <tr>
		<td><%= genre.name %></td>
	<% if user_signed_in? %>
		<td><%= link_to 'Show', genre %>&nbsp;
		<%= link_to 'Edit', edit_genre_path(genre) %>&nbsp;
		<%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
	  </tr>
	<% end %>
	</table>

	<% if user_signed_in? %>
	<br />

	<%= link_to 'New Genre', new_genre_path %>
	<% end %>
</div>

app/views/genres/new.html.erb
<h2>New genre</h2>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @genre.name %>
</p>


<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>