config/routes.rb
Rails.application.routes.draw do
	resources :archives, :only => [:index, :create, :edit, :destroy, :update] do
		collection do
			get 'category_list'
			get 'tree'
			get 'toggle_testing'
		end
	end

	resources :federations
	resources :genres
	resources :disciplines
	resources :white_lists

	post '/corrections' => 'corrections#create'

	resources :exhibits, :only => [:index, :create, :destroy] do
		collection do
			get 'test_create_good'
			get 'test_create_bad'
			get 'test_destroy_good'
			get 'test_destroy_bad'
		end
	end

	resources :locals, :only => [:index, :create, :destroy, :update ] do
		collection do
			get 'test_search_good'
			get 'test_search_bad'
		end
	end

	devise_for :users

	get "home/index"

   resources :pages, :only => [:index]

	resources :search, :only => [:index] do
		collection do
			get 'autocomplete'
			get 'names'
			get 'totals'
			get 'details'
			get 'compare'
      get 'languages'
		end
	end

	resources :test_sort, :only => [:index]

	get "/test_exception_notifier" => "home#test_exception_notifier"

  put "/documents/tw/enable" => "documents#typewright_enable"
  put "/documents/tw/disable" => "documents#typewright_disable"

  get "/documents/title" => "documents#title"

  root :to => "home#index"
	post "/" => "home#index"

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
	before_filter :must_be_logged_in, :except => [:index]
  # GET /disciplines
  # GET /disciplines.json
  # GET /disciplines.xml
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  # GET /disciplines/1.xml
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  # POST /disciplines.xml
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
        format.xml  { render :xml => @discipline, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
        format.xml  { render :xml => @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  # PATCH/PUT /disciplines/1.xml
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
        format.xml  { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
        format.xml  { render :xml => @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  # DELETE /disciplines/1.xml
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
      format.xml  { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:name)
    end
end

app/views/disciplines/_form.html.erb
<%= form_for(@discipline) do |f| %>
  <% if @discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% @discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
<h2>Editing discipline</h2>

<%= render 'form' %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>
</div>

app/views/disciplines/index.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
	<h2>All Disciplines</h2>
  <%= make_xml_path(request.fullpath) %><br/>
  <%= make_json_path(request.fullpath) %>

	<table class="results">
	  <tr>
		<th>Name</th>
	<% if user_signed_in? %>
		<th></th>
		<th></th>
		<th></th>
	<% end %>
	  </tr>

<% @disciplines.each do |discipline| %>
  <tr>
    <td><%= discipline.name %></td>
	<% if user_signed_in? %>
		<td><%= link_to 'Show', discipline %>&nbsp;
		<%= link_to 'Edit', edit_discipline_path(discipline) %>&nbsp;
		<%= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
  </tr>
<% end %>
</table>

	<% if user_signed_in? %>
<br />

<%= link_to 'New Discipline', new_discipline_path %>
	<% end %>
</div>

app/views/disciplines/new.html.erb
<h2>New discipline</h2>

<%= render 'form' %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @discipline.name %>
</p>


<%= link_to 'Edit', edit_discipline_path(@discipline) %> |
<%= link_to 'Back', disciplines_path %>