config/routes.rb
Rails.application.routes.draw do
	resources :archives, :only => [:index, :create, :edit, :destroy, :update] do
		collection do
			get 'category_list'
			get 'tree'
			get 'toggle_testing'
		end
	end

	resources :federations
	resources :genres
	resources :disciplines
	resources :white_lists

	post '/corrections' => 'corrections#create'

	resources :exhibits, :only => [:index, :create, :destroy] do
		collection do
			get 'test_create_good'
			get 'test_create_bad'
			get 'test_destroy_good'
			get 'test_destroy_bad'
		end
	end

	resources :locals, :only => [:index, :create, :destroy, :update ] do
		collection do
			get 'test_search_good'
			get 'test_search_bad'
		end
	end

	devise_for :users

	get "home/index"

   resources :pages, :only => [:index]

	resources :search, :only => [:index] do
		collection do
			get 'autocomplete'
			get 'names'
			get 'totals'
			get 'details'
			get 'compare'
      get 'languages'
		end
	end

	resources :test_sort, :only => [:index]

	get "/test_exception_notifier" => "home#test_exception_notifier"

  put "/documents/tw/enable" => "documents#typewright_enable"
  put "/documents/tw/disable" => "documents#typewright_disable"

  get "/documents/title" => "documents#title"

  root :to => "home#index"
	post "/" => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@query_params = QueryFormat.catalog_format()
		@autocomplete_params = QueryFormat.autocomplete_format()
		@names_params = QueryFormat.names_format()
		@uri_params= {'uri' => {:name => 'URI', :description => 'The URI of the object that you are interested in.'}}
		@locals_params = QueryFormat.locals_format()

		if request.post?
			render :partial => 'tabs'
		end
	end

	def test_exception_notifier
		raise "This is a test of the exception notification system. This is not a real error."
	end
end

app/helpers/home_helper.rb
module HomeHelper
	def example_link(link)
		return link_to(link, link.sub('.xml', ''), { :class => 'example_link' })
	end

	def tab_link(label, value, curr_tab)
		li_opts = {}
		li_opts[:class] = 'selected' if value == curr_tab
		return content_tag(:li,
			link_to(label, "/?tab=#{value}", { :class => "json_link json_history" }),
			li_opts)
	end
end

app/views/home/_compare_searching_options.html.erb
<p>This compares searches using different indexes and different Levenshtein distances.</p>
<p>The Indexes used are: Exact, Stemmed, and Stemmed w/diacriticals removed.</p>
<p>The three Levenshtein distances supported are: 0, 1, and 2.</p>
<p>(The result list are the unique terms found in the TEXT field for the first [Sample size] results.)</p>
<%= form_tag "/search/compare.json", method: 'get', id: 'search-compare', remote: true do %>
	<div><span class="label">Sample Size:</span>
		<input name="page_size" type="number" value="300" />
	</div>
	<div><span class="label">Federation:</span>
		<%= select_tag("fed", options_from_collection_for_select(Federation.all, "id", "name"), include_blank: "All") %>
	</div>
	<div><span class="label">Search Term:</span>
	<input name="q" type="text" />
	<input type="submit" value="Search" />
	</div>
<% end %>
<p id="progress-message"></p>
<h3>Results</h3>
<div id="compare-results">

</div>

app/views/home/_instructions.html.erb
<p>This is a quick synopsis of the indexing tasks that are done on a regular basis. They should be executed from the
	command line when in the <span class="code">~/www/catalog</span> folder. There are other rake tasks
	that can be done. See <span class="code">rake -T</span> for more info.
</p>
<h3>Initial indexing</h3>
<p>Use these steps when you get a brand new archive to index.</p>
<ol>
	<li>Update rdf/sitemap.yml
		<p>
			A line needs to be put into the sitemap file for each archive. The format is:<br /><span class="code">"archive_name": ["archive/folder", num_docs_to_process_at_once]</span>.<br />
			The line can be put in any section, but the archives are roughly ordered from small to large. If the archive has either a lot of documents, or each document has a large
			amount of text, it should be placed lower in the file. The <span class="code">archive_name</span> must EXACTLY match the archive in the RDF. You cannot mix
			archives in the same folder. The <span class="code">archive/folder</span> is the path that the RDF is, relative to the sitemap.yml file.
			The <span class="code">num_docs_to_process_at_once</span> should probably initially be 1000, then adjusted as needed. If you know that there is
			no full text, or that the full text is particularly small, then you can increase the number. After you've run the archive, at the bottom of the *_compare_text.log file
			there are some statistics about the size of the full text. You can use those numbers to tune this. The larger the number, the faster the comparison runs,
			but it may also run out of memory. The correct number is hard to say, but the one that corresponds to 5 megs is probably ok.
		</p>
	</li>
	<li>Check the RDF in to SVN
		<p>
			The RDF should be saved in a logical folder in the RDF section of the SVN repository. Usually it will either be at a top level folder (just under
			<span class="code">~/index/rdf/</span> if it is a one-off archive, or a single subfolder deeper if it is part of a larger collection. After checking it in from your machine, then it
			must be checked out on the ARC Catalog staging server. <span class="code">ssh</span> onto the ARC Catalog staging machine, <span class="code">cd ~/index/rdf</span> to the rdf folder,
				and do <span class="code">svn up</span> to get all the latest RDF.
		</p>
	</li>
	<li>Debugging the RDF
		<p>
			The first time you run a particular set of RDF, you will probably want to do a test run to see if there are errors in the XML format, or missing
			required fields. The following command will run through the indexing process without actually saving anything so it runs fast and there is
			no risk:<br />
			<span class="code">rake solr_index:debug archive=archive_name</span><br />
			(Note: all commands should be run from <span class="code">cd ~/www/catalog</span> on the server.) This will create this file:
			<span class="code">log/archive_name_error.log</span>. Study that file to see if the RDF is acceptable and repeat this step as necessary.
		</p>
	</li>
	<li>Getting the (raw) full text (that is, "spidering")
		<p>
			Some archives contain all the data inside the RDF, either because they don't have full text, or because the full text was embedded in the RDF.
			Other archives, however, require getting the full text from a website. If the RDF contains the element <span class="code">&lt;collex:text&gt;</span>
			and that element contains a URL, then this step is required to get the data. Run this:<br />
			<span class="code">rake solr_index:spider_rdf_text archive=archive_name</span><br />
			That will leave all the text that it found in the folder <span class="code">~/index/rawtext/archive_name</span>. Unfortunately, this data
			is often dirty in that it will contain html or other things that should not be included. If you determine that the data is completely clean, it
			can be copied over to <span class="code">~/index/fulltext/archive_name</span> and the following step can be skipped.
		</p>
	</li>
	<li>Process the raw text
		<p>
			At the moment, this step needs to be done by hand because there is no telling what is messy about the data. Any text processing tool can
			be used, but so far, we've extended the rdf-indexer for each archive we've encountered. The final result, though, should be a set of files in
			<span class="code">~/index/fulltext/archive_name</span> that is completely clean of extraneous material and is ready to be put in
			the index.
		</p>
	</li>
	<li>Indexing an archive
		<p>
			After the RDF is debugged and the fulltext is retrieved and cleaned, then you can index, using this command:<br />
			<span class="code">rake solr_index:index archive=archive_name</span><br />
			This will leave a number of files in <span class="code">cd ~/www/catalog/log/</span> that start with <span class="code">archive_name</span>.
			Study these files to see if there are any errors.
		</p>
	</li>
	<li>Test manually
		<p>
			The indexing process only creates a test archive. It is not in the general index yet. To see the result of the indexing, you must open the
			staging version of Collex in a browser, log in, then go to the admin page and click "Temporarily use the testing index for searches". You
			can then see if the index is acceptable. At this point, you can go to <%= link_to "Archives", "/archives", { class: 'example_link' } %>
			to add the archive to the resource tree.
		</p>
	</li>
	<li>Deploying the index
		<p>
			There are actually three copies of the solr index: there is a copy on production, but in staging, there is both a mirror of the deployed index, and also the test index. The
			above steps only put the new content in the test index. There is a step to copy that new content to the regular staging index, and a step
			to copy that new content to production. It is important to copy the content to the staging index, because future reindexing steps will use
			that to run tests against. To copy to the staging index:<br />
			<span class="code">rake solr_index:merge_archive archive=archive_name</span><br />
			After that finishes, you should see the archive on the staging server.
		</p>
		<p>
			To deploy it to production, there are two steps, one to run on the indexing server, and one to run on the production server. Run this on the indexing server:<br />
			<span class="code">rake solr_index:package archive=archive_name</span><br />
			This will request the login password for getting on the server. Then, after that finishes, ssh into the production ARC Catalog, and run this:<br />
			<span class="code">rake solr_index:install archive=archive_name</span><br />
			If, after installing an archive, you decide you don't want it in the index after all, you can remove an archive with:<br />
			<span class="code">rake solr_index:remove archive=archive_name</span><br />
			Note that you will have to repeat the step of adding the archive to the resource tree for the production server.
		</p>
	</li>
</ol>
<h3>Refreshing Text</h3>
<p>Use these steps when you want to download the full text again (after you have been informed that the content has changed).</p>
<ol>
	<li>Spidering and processing
		<p>
			Use the same two procedures for spidering and processing above (steps #4 and #5).
		</p>
	</li>
	<li>Reindexing
		<p>
			Because there is already an index, we would like to make sure that only the parts of the index that we intended to change
			have, in fact, been changed. The following command both performs the indexing and the testing:<br />
			<span class="code">rake solr_index:index_and_test archive=archive_name</span><br />
			This will leave a number of files in <span class="code">cd ~/www/catalog/log/</span> that start with <span class="code">archive_name</span>.
			Any change to the index will be flagged as an error. If you understand what the change was (that is, any text that is updated will be flagged), then
			there is no problem, but if an unusual error appears, then you may have introduced a regression error and it should be explained or fixed.
		</p>
	</li>
	<li>Deploying
		<p>The same steps for testing and deploying that were outlined above (steps #7, #8) should be done for deploying. You will not have
		to add the archive to the resource tree a second time, though.
		</p>
	</li>
</ol>
<h3>Reindexing an Archive</h3>
<p>When the RDF is modified, but the full text doesn't have to be downloaded again.</p>
<ol>
	<li>Follow the steps for refreshing text, except that you don't have to do the spidering steps.</li>
</ol>
<h3>Reindexing the entire index</h3>
<p>There are a number of reasons that the entire index must be reindexed. These include: when the version of solr is updated, when
	a schema change in solr has been done, when a bug in the indexing process as been discovered, and when an improvement to the indexing
	process has been done.
</p>
<p>
	Because reindexing takes some time, it is recommended to test the reindexing on a small same of archives first, so that you know the work
	is debugged before reindexing the entire index.
</p>
<ol>
	<li>Snapshot of all log files
		<p>
			To make sure that no regression errors sneak in, and that the intended change actually happened, first store all the log files in <span class="code">cd ~/www/catalog/log/</span>
			somewhere else. They will all get recreated, and we want to run a diff program on them to make sure we understand what the indexing process did.
		</p>
	</li>
	<li>Create new batch files
		<p>
			Once in a while, it is good to regenerate the indexing batch files. They will get out of date when new archives are added. Use this to regenerate them:<br />
			<span class="code">rake solr_index:create_reindexing_task_list</span><br />
			This will create a number of files in <span class="code">cd ~/www/catalog/tmp/</span> that are a convenience to reindexing.
		</p>
	</li>
	<li>Restart solr
		<p>
			If there were schema changes, you must restart solr. This will vary depending on how solr has been set up, but on the servers, it will
			generally be by restarting the solr service, like this: <span class="code">sudo /sbin/service solr restart</span> On your local machine,
			it might be using the rake task: <span class="code">rake solr:restart</span>
		</p>
	</li>
	<li>Run reindexing batch files
		To reindex everything, run:<br />
		<p>
		<span class="code">tmp/batch_all.sh</span><br />
		To reindex some indexes, run one of the smaller batch files:<br />
		<span class="code">tmp/batch1.sh</span><br />
		You may also run any of the commands in those batch files independently.
		</p>
	</li>
	<li>Compare and study log files
		<p>
			After reindexing, use a diff tool to compare the new log files with the original files.
		</p>
	</li>
	<li>Merging
		<p>
			When you are satisfied with the test index, you need to merge all the archives into the staging index. This can be done with:<br />
			<span class="code">tmp/merge_all.sh</span><br />
			It is safest to stop solr, delete the entire resources index, and restart solr before running this, but if you are sure that there have been
			no archives deleted, this isn't necessary.
		</p>
	</li>
	<li>Deploying
		<p>You can deploy all the archives as above, but that will be really tedious for each archive. Instead, you should just copy the entire archive
			over to the production machine, then re-add the exhibits:<br />
			Remove all exhibits, since they will be the exhibits from the staging site.<br />
			<span class="code">rake solr_index:delete_exhibits</span><br />
			That will take a while. Then zip up the index and send it to the server.<br />
			<span class="code">rake solr_index:package_resources</span><br />
			That will take a while, too. Then ssh to the production server and install the new index.<br />
			<span class="code">rake solr:replace_resources</span><br />
			This will take a long time, too, and the production server will be down during part of that time. Then re-add the exhibits, by logging into
			each of the federation's Collex, and running:<br />
			<span class="code">rake indexing:all_exhibits</span><br />
		</p>
	</li>
</ol>
<table class="help">
	<tr>
		<th>Other Commands</th>
		<th>Description</th>
	</tr>
	<tr>
		<td>all tasks with archive parameter</td>
		<td>The archive parameter can be either a single archive, or a comma separated list of archives (for example: rossetti,bierce) Depending on the
			OS, you may have to put quotes around the archive list.</td>
	</tr>
	<tr>
		<td>rake&nbsp;ecco:typewright_enable</td>
		<td>Mark texts for typewright (param: file=/text/file/path/one/item/per/line) This is expecting a text file with a list of 10-digit numbers, one per line.
			The numbers are the document numbers for the objects that should be typewright enabled.</td>
	</tr>
	<tr>
		<td>rake&nbsp;solr:examine</td>
		<td>examine solr document, both in the regular index and the reindexing index (param: uri=XXX text=yes|no) If you have the URI
			of a document, then you can see all the info that is saved in solr about it. Because the text will quickly overwhelm all other fields, there
			is the option of suppressing it. This shows the results in both the regular index and the testing index (if they exist.)
		</td>
	</tr>
	<tr>
		<td>rake&nbsp;solr_index:remove_archive</td>
		<td>removes the archive from the resources index (param: archive=XXX,YYY)</td>
	</tr>
	<tr>
		<td>rake&nbsp;solr_index:archive_test</td>
		<td>Test one RDF archive (param: archive=XXX,YYY). This tests the archive without rebuilding it. Its only effect is to refresh the .log files.</td>
	</tr>
	<tr>
		<td>rake&nbsp;solr:backup</td>
		<td>Backup the solr index specified. Leave a tar file in the backups folder. (param: index=XXX) [i.e. index=archive_rossetti]</td>
	</tr>

</table>

app/views/home/_params.html.erb
<%# params: (params => QueryFormat type object) %>
<table class="help">
	<tr>
		<th>Parameter</th>
		<th>Name</th>
		<th>Description</th>
	</tr>
	<% params.each { |key,val| %>
		<tr>
			<td><%= key %></td>
			<td><%= val[:name] %></td>
			<td><%= val[:description] %></td>
		</tr>
	<% } %>
</table>

app/views/home/_tabs.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<div class="nav_outer">
<ul class="nav<%= " narrow" if user_signed_in? %>">
	<% curr_tab = params[:tab] ? params[:tab] : 'overview' %>
	<%= tab_link("Overview", 'overview', curr_tab) %>
	<%= tab_link("Totals", 'totals', curr_tab) %>
	<%= tab_link("Search", 'search', curr_tab) %>
	<%= tab_link("Compare", 'compare', curr_tab) %>
	<%= tab_link("Autocomplete", 'autocomplete', curr_tab) %>
	<%= tab_link("Names Faceting", 'names', curr_tab) %>
	<%= tab_link("Details", 'uri', curr_tab) %>
	<%= tab_link("Meta", 'meta', curr_tab) %>
<% if user_signed_in? %>
		<%= tab_link("Exhibits", 'exhibits', curr_tab) %>
		<%= tab_link("User Content", 'user_content', curr_tab) %>
		<%= tab_link("Indexing", 'indexing', curr_tab) %>
<% end %>
</ul>
</div>
<div class="tab_content">
<% if params[:tab] == nil || params[:tab] == 'overview' %>
<div id="tab_overview" class="individual_tab">
    <h2>ARC Catalog</h2>
	<p>The ARC Catalog is a collection of metadata about the objects aggregated by NINES, 18thConnect and MESA. Using the web service, you can query these files without using the Collex interface provided by those sites.</p>
	<p>To use, call this in one of the ways indicated. It is designed to be used as a web service, but you can also type the
		values into your browser to interactively test your parameters. If you leave off the ".xml" in the following calls,
		the results will be formatted better for a browser.
	</p>
	<div class="special_notice">
	<h3>The ARC Catalog offers metadata from free-culture resources only.</h3>
	<p>
		<%= link_to "NINES",  "http://www.nines.org/about/scholarship/other-resources/", { class: 'ext', target: '_blank' } %> and
		<%= link_to "18thConnect", "http://www.18thconnect.org/about/community/major-contributors/", { class: 'ext', target: '_blank' } %>
		have made agreements with a number of commercial providers to offer metadata and some full-text searching of their
		materials through the Collex interface. The objects from these archives have been flagged in the
		<%= link_to "metadata", "http://www.performantsoftware.com/nines_wiki/index.php/Submitting_RDF#.3Ccollex:freeculture.3E", { class: 'ext', target: '_blank' } %>
		as proprietary, and will not be returned in queries submitted through the ARC Catalog.
	</p>
	<p>We will continue to revisit and review our agreements in the coming years, and post updates as the situation develops.</p>
	</div>

	<h3>Input format</h3>
	<p>
		Note that some characters are not allowed to be sent as part of a URL. If you want to use those characters they need
		to be escaped using a % and the hex code of the character. For instance, a plus sign should be encoded as <span class="code">%2B</span>.
	</p>
	<ul>
		<li>The input format follows the same syntax as URLs. In particular:</li>
		<li>The query parameters begin with a question mark.</li>
		<li>The query parameters are separated from each other with an ampersand (&amp;).</li>
		<li>A query parameter contains two parts: a key, followed by an equal sign, followed by a value.</li>
		<li>UTF-8 characters need to be escaped, so a query looks like: <span class="code">q=%2BBront%C3%AB</span> instead of the more natural: <span class="code">q=%2BBrontë</span> </li>
		<li>The plus sign and a number of other symbols are used in a lot of places, and need to be escaped to be used in a URL. Here are some common substitutions:
			<table class="ascii_table">
				<tr><th>Character</th><th>Escape</th></tr>
				<tr class='important'><td>space</td><td>+</td></tr>
				<tr><td>#</td><td>%23</td></tr>
				<tr><td>$</td><td>%24</td></tr>
				<tr><td>%</td><td>%25</td></tr>
				<tr><td>&amp;</td><td>%26</td></tr>
				<tr><td>'</td><td>%27</td></tr>
				<tr class='important'><td>+</td><td>%2B</td></tr>
				<tr><td>.</td><td>%2E</td></tr>
				<tr><td>/</td><td>%2F</td></tr>
				<tr class='important'><td>:</td><td>%3A</td></tr>
				<tr><td>;</td><td>%3B</td></tr>
				<tr><td>&lt;</td><td>%3C</td></tr>
				<tr><td>=</td><td>%3D</td></tr>
				<tr><td>&gt;</td><td>%3E</td></tr>
				<tr><td>?</td><td>%3F</td></tr>
				<tr><td>@</td><td>%40</td></tr>
				<tr><td>[</td><td>%5B</td></tr>
				<tr><td>\</td><td>%5C</td></tr>
				<tr><td>]</td><td>%5D</td></tr>
				<tr><td>^</td><td>%5E</td></tr>
				<tr><td>`</td><td>%60</td></tr>
				<tr><td>{</td><td>%7B</td></tr>
				<tr><td>|</td><td>%7C</td></tr>
				<tr><td>}</td><td>%7D</td></tr>
				<tr><td>~</td><td>%7E</td></tr>
 			</table>
		</li>
	</ul>
</div>

<% elsif params[:tab] == 'totals' %>
<div id="tab_totals" class="individual_tab">
	<h3>Totals</h3>
	<p>This gives an overview of the number of documents and the number of archives that are in the catalog.</p>
	<p>Call <%= example_link("/search/totals.xml") %> to get a list of all the federations and how many documents and archives they contain.</p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/totals.xsd", { :class => 'example_link' } %></p>
</div>

<% elsif params[:tab] == 'search' %>
<div id="tab_search" class="individual_tab">
	<h3>Full Text Searching</h3>
	<p>Any field that is collected can be searched for, including the full text of the document.</p>
	<p>Note: All searches are case-insensitive and punctuation cannot be searched for.</p>
	<p>Call <span class="code">/search.xml</span> with the following parameters:</p>
	<%= render :partial => 'params', :locals => { :params => @query_params } %>
	<p>Example: Search for all mention of "tree" by Williams: <%= example_link("/search.xml?q=%2btree&aut=%2bWilliams") %></p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/search_results.xsd", { :class => 'example_link' } %></p>
</div>

<% elsif params[:tab] == 'compare' %>
<div id="tab_compare" class="individual_tab">
	<h3>Compare Searching Options</h3>
	<%= render "compare_searching_options" %>
</div>

<% elsif params[:tab] == 'autocomplete' %>
<div id="tab_autocomplete" class="individual_tab">
	<h3>Searching to Facilitate Auto-completion</h3>
	<p>A query can be submitted character by character to allow you to prompt the user for queries that will succeed.
		You can specify the number of items that you want to present, and the results will contain the number of hits
		that the queries will generate.
	</p>
	<p>This is designed to be used to implement auto-complete functionality. Either the entire index can be searched with auto-complete
		or you may search just a portion of the index by including other parameters.
	</p>
	<p>Call <span class="code">/search/autocomplete.xml</span> with the following parameters:</p>
	<%= render :partial => 'params', :locals => { :params => @autocomplete_params } %>
	<p>Example: Auto-complete "tre" (top 25 results): <%= example_link("/search/autocomplete.xml?frag=tre&max=25") %></p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/autocomplete_results.xsd", { :class => 'example_link' } %></p>
</div>

<% elsif params[:tab] == 'names' %>
<div id="tab_names" class="individual_tab">
	<h3>Names Faceting</h3>
	<p>This is to get a list of all the names (authors, publishers, and editors) that are associated with a particular query.</p>
	<p>Call <span class="code">/search/names.xml</span> with the following parameters:</p>
	<%= render :partial => 'params', :locals => { :params => @names_params } %>
	<p>Example: All authors, publishers, and editors who mention "tree" and Williams: <%= example_link("/search/names.xml?q=%2btree%2bWilliams") %></p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/names_results.xsd", { :class => 'example_link' } %></p>
</div>

<% elsif params[:tab] == 'uri' %>
<div id="tab_uri" class="individual_tab">
	<h3>Querying for a particular object.</h3>
	<p>This is designed to get all the fields for a specific object if you already know what the object is. Usually it would be used if you had already done a search in the past.
		You can save the uri from the first search, and retrieve the details later using this call.
	</p>
	<p>Call <span class="code">/search/details.xml</span> with the following parameters:</p>
	<%= render :partial => 'params', :locals => { :params => @uri_params } %>
	<p>Example: A document by Whitman: <%= example_link("/search/details.xml?uri=http%3a%2f%2fwww%2ewhitmanarchive%2eorg%2fcriticism%2freviews%2fleaves%2fleaves55%2fdailytimes") %></p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/search_results.xsd", { :class => 'example_link' } %></p>
</div>

<% elsif params[:tab] == 'meta' %>
<div id="tab_meta" class="individual_tab">
	<h3>Other information</h3>
	<p>You can also get information about the items that make up the index with one of these calls:</p>
	<p><%= example_link("/archives.xml") %> : To get a list of all the possible archives, and their parameters.</p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/meta_archives.xsd", { :class => 'example_link' } %></p>
	<p><%= example_link("/genres.xml") %> : To get a list of all the possible genres</p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/meta_genres.xsd", { :class => 'example_link' } %></p>
    <p><%= example_link("/disciplines.xml") %> : To get a list of all the possible disciplines</p>
    <p>The output format is described in this <%= link_to "XSD", "/xsd/meta_disciplines.xsd", { :class => 'example_link' } %></p>
	<p><%= example_link("/federations.xml") %> : To get a list of all the possible federations, and their thumbnails.</p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/meta_federations.xsd", { :class => 'example_link' } %></p>
</div>

<% elsif params[:tab] == 'exhibits' && user_signed_in? %>
<div id="tab_exhibits" class="individual_tab">
	<h3>Exhibits</h3>
	<p>Exhibits can be indexed like this:</p>
	<p><%= example_link("/exhibits.xml") %></p>
</div>

<% elsif params[:tab] == 'user_content' && user_signed_in? %>
<div id="tab_user_content" class="individual_tab">
	<h3>User Content</h3>
	<p>A secondary index can be read and written from too:</p>
	<%= render :partial => 'params', :locals => { :params => @locals_params } %>
	<p>Example: <%= example_link("/locals.xml?q=%2brossetti&section=community&object_type=Exhibit&federation=NINES") %></p>
	<p>The output format is described in this <%= link_to "XSD", "/xsd/locals_results.xsd", { :class => 'example_link' } %></p>
</div>

<% elsif params[:tab] == 'indexing' && user_signed_in? %>
<div id="tab_indexing" class="individual_tab">
	<%= render :partial => 'instructions' %>
</div>
<% end %>
</div> <%# tab content %>

<div class="admin">
<% if user_signed_in? %>
        <%= link_to "Manage genres", genres_path %> | <%= link_to "Manage disciplines", disciplines_path %> | <%= link_to "Manage archives", archives_path %> | <%= link_to "Manage federations", federations_path %> | <%= link_to "Manage white list", white_lists_path %> | <%= link_to "Log out", destroy_user_session_path, :method=>'delete' %>
<% else %>
<%= link_to "admin", new_user_session_path %>
<% end %>
</div>

app/views/home/error.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
	<h2>Error</h2>
	<div class="error_msg"><%= @error_msg %></div>
	<div>Requested URL: <span class="error_info"><%= @original_request %></span></div>
	<div>Response status: <span class="error_info"><%= @status.to_s %></span></div>
</div>

app/views/home/index.html.erb
<%= render :partial => 'tabs' %>