config/routes.rb
Rails.application.routes.draw do
	resources :archives, :only => [:index, :create, :edit, :destroy, :update] do
		collection do
			get 'category_list'
			get 'tree'
			get 'toggle_testing'
		end
	end

	resources :federations
	resources :genres
	resources :disciplines
	resources :white_lists

	post '/corrections' => 'corrections#create'

	resources :exhibits, :only => [:index, :create, :destroy] do
		collection do
			get 'test_create_good'
			get 'test_create_bad'
			get 'test_destroy_good'
			get 'test_destroy_bad'
		end
	end

	resources :locals, :only => [:index, :create, :destroy, :update ] do
		collection do
			get 'test_search_good'
			get 'test_search_bad'
		end
	end

	devise_for :users

	get "home/index"

   resources :pages, :only => [:index]

	resources :search, :only => [:index] do
		collection do
			get 'autocomplete'
			get 'names'
			get 'totals'
			get 'details'
			get 'compare'
      get 'languages'
		end
	end

	resources :test_sort, :only => [:index]

	get "/test_exception_notifier" => "home#test_exception_notifier"

  put "/documents/tw/enable" => "documents#typewright_enable"
  put "/documents/tw/disable" => "documents#typewright_disable"

  get "/documents/title" => "documents#title"

  root :to => "home#index"
	post "/" => "home#index"

end

app/models/federation.rb
class Federation < ActiveRecord::Base
   before_save :update_carousel

   belongs_to :carousel, :inverse_of => :federation
   has_attached_file :thumbnail,
                    :styles => { :thumb => "220x80>" },
                    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
                    :url => "/system/:attachment/:id/:style/:filename"
   validates_attachment_size :thumbnail, :less_than => 5.megabytes,  :unless => Proc.new {|m| m[:thumbnail].nil?}
   validates_attachment_content_type :thumbnail, :content_type => ['image/jpeg', 'image/png', 'image/gif'], :unless => Proc.new {|m| m[:thumbnail].nil?}

   def self.request_from_federation(ip)
      # If the ip is on the white list, it can be used.
      white_list = WhiteList.where(ip: ip)
      return true if white_list.length > 0

      # This checks to see if the ip address of the caller matches any of the
      # federations.
      fed = Federation.find_by({ ip: ip })
      #return false
      return fed != nil
   end

   private

   def update_carousel
      if self.carousel.nil?
         self.carousel = Carousel.new(:name => self.name)
      else
         self.carousel.name = self.name
         self.carousel.save
      end
   end

end

app/controllers/federations_controller.rb
class FederationsController < ApplicationController
  before_action :set_federation, only: [:show, :edit, :update, :destroy]
#	before_filter :must_be_logged_in
	before_filter :must_be_logged_in, :except => [:index]

  # GET /federations
  # GET /federations.json
  # GET /federations.xml
  def index
    @federations = Federation.all
  end

  # GET /federations/1
  # GET /federations/1.json
  # GET /federations/1.xml
  def show
  end

  # GET /federations/new
  # GET /federations/new.xml
  def new
    @federation = Federation.new
  end

  # GET /federations/1/edit
  def edit
  end

  # POST /federations
  # POST /federations.json
  # POST /federations.xml
  def create
    @federation = Federation.new(federation_params)

    respond_to do |format|
      if @federation.save
        format.html { redirect_to @federation, notice: 'Federation was successfully created.' }
        format.json { render :show, status: :created, location: @federation }
        format.xml  { render :xml => @federation, :status => :created, :location => @federation }
      else
        format.html { render :new }
        format.json { render json: @federation.errors, status: :unprocessable_entity }
        format.xml  { render :xml => @federation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /federations/1
  # PATCH/PUT /federations/1.json
  # PATCH/PUT /federations/1.xml
  def update
    respond_to do |format|
      if @federation.update(federation_params)
        format.html { redirect_to @federation, notice: 'Federation was successfully updated.' }
        format.json { render :show, status: :ok, location: @federation }
        format.xml  { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @federation.errors, status: :unprocessable_entity }
        format.xml  { render :xml => @federation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /federations/1
  # DELETE /federations/1.json
  # DELETE /federations/1.xml
  def destroy
    @federation.destroy
    respond_to do |format|
      format.html { redirect_to federations_url, notice: 'Federation was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_federation
      @federation = Federation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def federation_params
      params.require(:federation).permit(:name, :ip, :site, :thumbnail)
    end
end

app/views/federations/_form.html.erb
<%= form_for(@federation, :html => { :multipart => true }) do |f| %>
	<% if @federation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@federation.errors.count, "error") %> prohibited this federation from being saved:</h2>

      <ul>
      <% @federation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
	  <%= f.label :name %><br>
	  <%= f.text_field :name %>
	</div>
	<div class="field">
	  <%= f.label :ip %><br>
	  <%= f.text_field :ip %>
	</div>
	<div class="field">
	  <%= f.label :site %><br>
	  <%= f.text_field :site %>
	</div>
	<div class="field">
	  <%= f.label :thumbnail %><br>
		<%= f.file_field :thumbnail %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/federations/edit.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
	<h2>Editing federation</h2>

	<%= render 'form' %>

	<%= link_to 'Show', @federation %> |
	<%= link_to 'Back', federations_path %>
</div>

app/views/federations/index.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
	<h2>All Federations</h2>
  <%= make_xml_path(request.fullpath) %><br/>
  <%= make_json_path(request.fullpath) %>

	<table class="results">
	  <tr>
		  <th>Name</th>
		  <th>Thumbnail</th>
		  <th>Site</th>
	<% if user_signed_in? %>
		  <th>IP</th>
		<th></th>
		<th></th>
		<th></th>
	<% end %>
	  </tr>

	<% @federations.each do |federation| %>
	  <tr>
		  <td><%= federation.name %></td>
		  <td><%= image_tag federation.thumbnail.url(:thumb) %></td>
		  <td><%= federation.site %></td>
	<% if user_signed_in? %>
	    <td><%= federation.ip %></td>
		<td><%= link_to 'Show', federation %>&nbsp;
		<%= link_to 'Edit', edit_federation_path(federation) %>&nbsp;
		<%= link_to 'Destroy', federation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
        </td>
	<% end %>
	  </tr>
	<% end %>
	</table>

	<% if user_signed_in? %>
	    <br />
	    <%= link_to 'New Federation', new_federation_path %>
	<% end %>
</div>

app/views/federations/new.html.erb
<%= make_home_path %>
<div class="tab_content">
	<p id="notice"><%= notice %></p>
	<h2>New federation</h2>

	<%= render 'form' %>

	<%= link_to 'Back', federations_path %>
</div>

app/views/federations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @federation.name %>
</p>


<%= link_to 'Edit', edit_federation_path(@federation) %> |
<%= link_to 'Back', federations_path %>